model: FlowCF

# [수정 1] 실제 폴더 이름과 똑같이 맞춰야 합니다.
dataset: BPR_cv  

gpu_id: '0'
log_wandb: False

# [수정 2] data_path는 'BPR_cv' 폴더가 들어있는 '부모 폴더'까지만 적습니다.
# RecBole이 자동으로 /app/dataset/ML1M/ + BPR_cv/ 를 합쳐서 경로를 만듭니다.
data_path: /app/dataset/ML1M/

# [나머지는 그대로 유지]
benchmark_filename: ['train', 'vali', 'test']
field_separator: "\t"
USER_ID_FIELD: mid
ITEM_ID_FIELD: uid
RATING_FIELD: rating
TIME_FIELD: null
load_col:
    inter: [uid, mid, rating]
user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
alias_of_user_id: ~
alias_of_item_id: ~

# 모델 파라미터 (기존 유지)
n_steps: 20
s_steps: 10
dims_mlp: [2000, 2000, 2000, 2000]
time_embedding_size: 64
dropout: 0.2
epochs: 300
train_batch_size: 4096
learning_rate: 0.0005
eval_step: 1
stopping_step: 30

# [실험 옵션]
prior_type: 'bernoulli'  # 'gaussian' 또는 'bernoulli'
act_func: 'leakyrelu'        # 'gelu' 또는 'leakyrelu'